# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.cert_manager.acme.v1 import Challenge as _Resource2
    from cloudcoil.models.cert_manager.acme.v1 import Order as _Resource5
    from cloudcoil.models.cert_manager.v1 import Certificate as _Resource0
    from cloudcoil.models.cert_manager.v1 import CertificateRequest as _Resource1
    from cloudcoil.models.cert_manager.v1 import ClusterIssuer as _Resource3
    from cloudcoil.models.cert_manager.v1 import Issuer as _Resource4

_MODELS = {
    ("Certificate", "cert-manager.io/v1"): ("cloudcoil.models.cert_manager.v1", "Certificate"),
    ("Certificate", ""): ("cloudcoil.models.cert_manager.v1", "Certificate"),
    ("CertificateRequest", "cert-manager.io/v1"): (
        "cloudcoil.models.cert_manager.v1",
        "CertificateRequest",
    ),
    ("CertificateRequest", ""): ("cloudcoil.models.cert_manager.v1", "CertificateRequest"),
    ("Challenge", "acme.cert-manager.io/v1"): (
        "cloudcoil.models.cert_manager.acme.v1",
        "Challenge",
    ),
    ("Challenge", ""): ("cloudcoil.models.cert_manager.acme.v1", "Challenge"),
    ("ClusterIssuer", "cert-manager.io/v1"): ("cloudcoil.models.cert_manager.v1", "ClusterIssuer"),
    ("ClusterIssuer", ""): ("cloudcoil.models.cert_manager.v1", "ClusterIssuer"),
    ("Issuer", "cert-manager.io/v1"): ("cloudcoil.models.cert_manager.v1", "Issuer"),
    ("Issuer", ""): ("cloudcoil.models.cert_manager.v1", "Issuer"),
    ("Order", "acme.cert-manager.io/v1"): ("cloudcoil.models.cert_manager.acme.v1", "Order"),
    ("Order", ""): ("cloudcoil.models.cert_manager.acme.v1", "Order"),
}


@overload
def get_model(
    kind: Literal["Certificate"], *, api_version: Literal["cert-manager.io/v1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Certificate"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["CertificateRequest"], *, api_version: Literal["cert-manager.io/v1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["CertificateRequest"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["Challenge"], *, api_version: Literal["acme.cert-manager.io/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(kind: Literal["Challenge"], *, api_version: Literal[""] = "") -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ClusterIssuer"], *, api_version: Literal["cert-manager.io/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["ClusterIssuer"], *, api_version: Literal[""] = ""
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["Issuer"], *, api_version: Literal["cert-manager.io/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(kind: Literal["Issuer"], *, api_version: Literal[""] = "") -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["Order"], *, api_version: Literal["acme.cert-manager.io/v1"]
) -> type[_Resource5]: ...


@overload
def get_model(kind: Literal["Order"], *, api_version: Literal[""] = "") -> type[_Resource5]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
